export default {
  TOGGLE_SIDER: 'TOGGLE_SIDER',
  TAB_CARD: 'TAB_CARD',
  MODAL: 'MODAL',
  FLIGHT_LIST: 'FLIGHT_LIST',
  PASSENGER_LIST: 'PASSENGER_LIST',
  AIRPORT_LIST: 'AIRPORT_LIST',
  STEP: 'STEP',
  ID: 'ID',
  INFO: 'INFO'
}
