export default {
  TOGGLE_SIDER: 'TOGGLE_SIDER',
  TAB_CARD: 'TAB_CARD',
  MODAL: 'MODAL',
  FLIGHT_LIST: 'FLIGHT_LIST',
  PASSENGER_LIST: 'PASSENGER_LIST',
  AIRPORT_LIST: 'AIRPORT_LIST',
  STEP: 'STEP',
  ID: 'ID',
  INFO: 'INFO',
  MESSAGE: 'MESSAGE',
  CHECKIN_LIST: 'CHECKIN_LIST',
  SECURITY_LIST: 'SECURITY_LIST',
  COUNTER: 'COUNTER',
  LOG_OUT: 'LOG_OUT',
  LUGGAGE: 'LUGGAGE'
}
